### ISSUE TITLE
Example request - alternate function mapping / pin mux

### ISSUE THREAD

**Issue by prosper00** [cnlohr/ch32v003fun#142]
Some pins on the 8-pin package have multiple functions, as well as multiple assignments.

Port D4 and port D5 are both listed as available on pin 8, for example, as well as having default and remapped functions available for each. I would find it helpful to have an example showing how to select between GPIOs on that pin, as well as between the alternate functions. (e.g. an example implementation of the content discussed in chapter 7 of the RM http://www.wch-ic.com/downloads/file/358.html )

![Screenshot_2023-05-30_09-47-44](https://github.com/cnlohr/ch32v003fun/assets/57373245/a3e0c574-f97f-4fb0-bfbc-ee9dd8be292c)

**Comment by GerardoNevarez** [comment]
All default functions for these "muxed" pins are available by default. When you set, say, pin8 as UTX, you can no longer use it for programming the IC.

See the various examples that are already present, the short version is that _both_ default and alternative functions have to be explicitly set, by changing configuration registers for each port

**Comment by dwillmore** [comment]
There isn't another set of 'alternate function' registers for these
combined pins.  We haven't verified this by decapsulating a chip, but it's
likely that both pads on the chip have been bonded to the one pad on the
lead frame of the package.

You could enable one of those 'pins' (from the perspective of the chip) as
well as the other 'pin' which share a package pin as long as they don't
both try to drive different signals.  If one was input only and the other
set to output, you could do that.  I'm not sure how useful it might be.

Another possibility is to increase the drive output of a package pin by
enabling both of the internal pins as output and driving them
simultaniously.  Experiments have yet to be done to gauge the possible
benefit of that.

**Comment by prosper00** [comment]
Interesting. That was my reaction - 'what if I write a 'high' to PD4 and a 'low' to PD5?' Seems likely to be a smoke-emitting configuration.

If I enable a peripheral on PD4, will it disable all the peripherals on PD5 - or do I just have to be careful? 

in any case, my original question has been answered, and it's really quite simple. 


Thanks!

**Comment by dwillmore** [comment]
The current untested theory is you have to be careful. :)  It very well may
emit smoke if mishandled. :)  Proceed with caution.  If you learn anything,
please come back here and start a discussion to share your knowledge.
