### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by dquadros** [cnlohr/ch32v003fun#154]
The link for the Prep wiki page is broken (text and url are exchanged):

`[https://github.com/cnlohr/ch32v003fun/wiki/Installation](wiki page here)`

should be

`[wiki page here](https://github.com/cnlohr/ch32v003fun/wiki/Installation)`

**Comment by dwillmore** [comment]
The wiki is editable, so feel free.  And thank you for catching my mistake!

**Comment by cnlohr** [comment]
Except this was the readme.  And it was my fault.

Thanks for catching it, @dquadros
