### ISSUE TITLE
minichlink doesn't support gdb "load"

### ISSUE THREAD

**Issue by maxgerhardt** [cnlohr/ch32v003fun#159]
```
$ riscv-none-embed-gdb -ex "target remote :2000" blink.elf
..
(gdb) set debug remote 1
(gdb) load
Sending packet: $vFlashErase:00000000,00000200#bc...Ack
Packet received: 
Remote target does not support flash erase
```

That should be easy to implement especially since the tool can flash already..

**Comment by cnlohr** [comment]
What does `set debug remote 1` do?

**Comment by maxgerhardt** [comment]
That makes gdb show debug output for the remote data it sends to the gdbserver. Just for reference so you know what the request packet looks like that minichlink should handle.

**Comment by cnlohr** [comment]
aaah gotcha

**Comment by cnlohr** [comment]
What version of GDB are you testing on?

**Comment by maxgerhardt** [comment]
Still 8.3. same as in #158.

**Comment by cnlohr** [comment]
Sorry this took so long to resolve, but it should all work now.
