### ISSUE TITLE
Onewire slave emulation

### ISSUE THREAD

**Issue by phantomxe** [cnlohr/ch32v003fun#177]
I want to emulate a onewire device with using cheap ch32v003. I found some examples developed for other architectures like AVRs or PICs. 

https://github.com/cogsy23/aowslave
https://github.com/MarkusLange/OneWireSlave
https://github.com/lamlamngo/onewire-slave-emulator

All of them are interrupt driven, I tried to write my code with ch32v003fun. But interrupt example is not very clear. For example, i need falling and rising (change) interrupts for PC1. Also i need cli and sei commands on AVRs.
 ```
#define cli() (NVIC_DisableIRQ( EXTI7_0_IRQn ))
#define sei() (NVIC_EnableIRQ( EXTI7_0_IRQn ))
 ``` 
Is that ok or not? How can i use it properly?

**Comment by cnlohr** [comment]
You don't need to stop interrupts if you are in one.  cli/sei aren't a single instruction but they are probably better to be `__disable_irq` / `__enable_irq`.

You would need to show me more code if you are struggling to get info on how to improve your interrupt code.

**Comment by phantomxe** [comment]
PD3 with rising edge trigger used in pin change example code;

``` 
// Configure the IO as an interrupt.
AFIO->EXTICR = 3<<(3*2); //PORTD.3 (3 out front says PORTD, 3 in back says 3)
EXTI->INTENR = 1<<3; // Enable EXT3
EXTI->RTENR = 1<<3;  // Rising edge trigger

// enable interrupt
NVIC_EnableIRQ( EXTI7_0_IRQn );
```

I'm try to write both rising and falling trigger for pc1.
```
AFIO->EXTICR = 2<<(1*2);  
EXTI->INTENR = 1<<3; 
EXTI->RTENR = 1<<3;  
EXTI->FTENR = 1<<3;  
```
Is it correct?

**Comment by cnlohr** [comment]
I believe that is also correct, generally.

**Comment by phantomxe** [comment]
I made a little progress. https://github.com/phantomxe/ch32v003_ow/tree/main/ow_probe_adc

Also combined with ADC DMA example. But i got some triggering problems at reset state. Is it possible to check my code in terms of interrupt usage or general structure? @cnlohr

**Comment by cnlohr** [comment]
I am not quite sure what I should be searching for.

One thing makes me anxious is the `EXTI7_0_IRQHandler` interrupt - You should probably use a state machine, either with a `switch` statement or a function pointer to the current state,  It will prevent a lot of branches.  Branches on the CH32V003 are expensive.

**Comment by cnlohr** [comment]
I am still interested in seeing this come to fruition.  Any chance you would still get it further over the finish line?

**Comment by cw2** [comment]
I apologize in advance for hijacking this thread with potentially irrelevant information, but if I remember it correctly it is not possible to emulate the 1-wire protocol in a slave device unless you have a proper Maxim/Dallas license (or use genuine Maxim/Dallas part). Unfortunately, I could not find the original document with the information, only informal mentions on the internet. IANAL so it might be fine to use 1-wire slave device emulation for e.g. educational purposes, but if you plan to use it commercially, I would recommend checking with the company legal department.

Sorry again and thank you for your understanding.

**Comment by phantomxe** [comment]
@cw2 Thanks for your attention. I just on the educational zone.
@cnlohr I used to think that I had a knowledge about development on embedded systems. But after i started with experimenting on ch32v003fun, i found my knowledge is mediocre. After several weeks of development with logic analyzer, It worked partially. It can sense the reset and respond with presence pulse, read-write operations are possible. I want to combine with adc dma example. I tried to send ADC data over scratchpad but it's not working.
```c
//so I'm not going to do temperature conversion at now 
scratchpad[0] = (uint8_t)(adc_buffer[0] & 0xFF); // FIXME not working
scratchpad[1] = (uint8_t)((adc_buffer[0] >> 8) & 0xFF);   
scratchpad[2] = 0x31; // for debugging
```
And i refactored if-else statements to switch-case. You can have a look at my latest code in the repository. But I don't understand that why i can't run any printf, adc on main loop when onewire stuff is working on interrupt. Sorry for the inconvenience.

**Comment by mstegen** [comment]
Just to add to this old issue, as i'm also trying to implement a onewire slave in software on a v003.
The patent from Maxim seems to have expired in 2016. https://patents.google.com/patent/US5210846B1/en
So i think it's ok to emulate it, even for commercial use.

**Comment by cnlohr** [comment]
I would be curious to see it as well... If you make a demo, I'm happy to review and if good, accept
