### ISSUE TITLE
NRST mention in README

### ISSUE THREAD

**Issue by mengstr** [cnlohr/ch32v003fun#181]
The readme says `Optional (not needed, can be configured as output if fuse set): NRST is on PD7`. 
To avoid unnecessary confusion and datasheet reading It might be good to mention that PD7 by default is a GPIO.

<img width="917" alt="ch32reset" src="https://github.com/cnlohr/ch32v003fun/assets/325326/43305af3-e1cc-48e2-9347-159862790422">

**Comment by cnlohr** [comment]
Do you have a proposal on how to convey it clearly?

**Comment by mengstr** [comment]
LOL no...  As a non-native English speaker that recently, even for my own mother tongue, got low scores on "clarity of communication" in the yearly evaluation at my workplace I might not be the best person to ask :-)

Maybe just invert the context of the sentence? 
`Optional: NRST on PD7 (not needed, but be configured if the RST_MODE fuses in flash are modified) `

**Comment by cnlohr** [comment]
I rejiggerd it some.  I think it's good - closing issue now.
