### ISSUE TITLE
Add deep sleep example

### ISSUE THREAD

**Issue by cnlohr** [cnlohr/ch32v003fun#191]

**Comment by recallmenot** [comment]
Isn't standby the lowest power mode:
https://github.com/cnlohr/ch32v003fun/tree/master/examples/standby_autowake

**Comment by cnlohr** [comment]
Actually yes.  It is.  Could definitely use more comments explaining it.  I am not sure how to apply very much of it.  I can work from there.  Thank you for pointing that out.

**Comment by cnlohr** [comment]
I guess I'll close for now.

**Comment by recallmenot** [comment]
https://github.com/recallmenot/ch32v003fun_wildwest/tree/main/proj/standby_autowake_and_btn
https://github.com/recallmenot/ch32v003fun_wildwest/blob/main/lib/ch32v003_standby.h
might these be helpful?

**Comment by cnlohr** [comment]
Reopening until it's solved - these seem to use 100-200uA?

**Comment by eeucalyptus** [comment]
Telling by the git history, the problem was a missing power cycle after programming (see https://github.com/cnlohr/ch32v003fun/commit/8b05efb3d8254084cc1eabf40d54b32319cf1219)
