### ISSUE TITLE
Incorrect timer in pinout

### ISSUE THREAD

**Issue by MartinEssink** [cnlohr/ch32v003fun#211]
The pinout for the CH32V003F4P6 in the readme has T1 and T2 switched for PD3/Pin20. According to the datasheet the channels on this pin are T2CH2 and T1CH4_.

**Comment by Tengo10** [comment]
The image generation had a bug, should be fixed now.
If you find any more problems feel free to bring them up over at: https://github.com/Tengo10/pinout-overview where the overviews are generated.
