### ISSUE TITLE
debugprintfdemo bricks CH32V003J4M6 since SWIO and PD4 share the same PIN

### ISSUE THREAD

**Issue by limingjie** [cnlohr/ch32v003fun#219]
# Root Cause
The `SWIO` and `PD4` share the same PIN on CH32V003J4M6. In the `debugprintfdemo`, `PD4` is used for output, after flashing the chip is bricked since `SWIO` is taken as `PD4`.

# Solution
- The `debugprintfdemo` should avoid using `PD4`.
- The command `minichlink -ua` can unbrick the chip. However, if the chip was connected to the WCH-LinkE for a long time, it could be damaged. For me, one chip is unbricked, and another is too hot and damaged.

![image](https://github.com/cnlohr/ch32v003fun/assets/6889308/bc454c13-f179-4fff-9fc9-852d7d9c34e3)

**Comment by cnlohr** [comment]
PR accepted.

What was WCH thinking when they put those pins together????

**Comment by limingjie** [comment]
Thank you! I was also wondering why they share the SWIO pin, to easily brick the chip and make more earnings? LOL.

Luckily, the `minichlink` can unbrick the chip, great tool! Thanks again!
