### ISSUE TITLE
minimal gcc project

### ISSUE THREAD

**Issue by mrx23dot** [cnlohr/ch32v003fun#242]
I created this minimal project based on gcc, instead of platform.io magicware,
feel free to use it or mention it as an alternative.

https://github.com/mrx23dot/ch32v003_minimal_gcc

**Comment by eeucalyptus** [comment]
It looks quite nice but a little bit redundant, since ch32v003fun is also a pure makefile project (yes with optional pio support). What are the goals with your approach? How do they differ from this projects goals?

**Comment by cnlohr** [comment]
I don't understand how we can do things to help facilitate that?  We already have the `template` example, which only requires the ch32v003fun folder + _some_ libgcc.a.

**Comment by mengstr** [comment]
Maybe we could have a "ch32v003starter" that just contains the essential parts.
That is the 

- ch32v003fun/  -folder
- Makefile
- funconfig.h
- main.c (with just stubs)

It would be nice if the makefile could pull the latest version of the ch32v003fun as well. I do it like this:
```
ch32v003fun:
	@echo Getting fresh copy of ch32v003fun from github
	@rm -rf ch32v003fun tmpfun
	@git clone --depth 1 https://github.com/cnlohr/ch32v003fun.git tmpfun
	@cp tmpfun/misc/libgcc.a tmpfun/ch32v003fun
	@mv tmpfun/ch32v003fun/ . 
	@rm -rf tmpfun
	@$(CC) $(CFLAGS) -c -o ch32v003fun/ch32v003fun.o ch32v003fun/ch32v003fun.c
```

**Comment by cnlohr** [comment]
So it's the examples folder that you don't like?

**Comment by mengstr** [comment]
I thought that you liked minimal projects and stuff?  ;-)

For me it's perfectly usable as it is. It's not too much of a hassle to remove all non-essential bits and bobs when I start a new project - the Makefile takes care of that automatically. But it would be kinda nice to get a plain starter kit that you just can "clone and go". 

I mean you don't want a lot of unused files with code and other detritus in your project, especially if you upload it to GitHub or publish it another way. For GitHub a .gitignore that removes all non-project files and folders could suffice. But why have the project folders in your local project filled with clutter.

Don't get me wrong, I love having access to the examples, they are a very important part of ch32v003fun. I wouldn't want to be without them. But I don't want them in my code.
