### ISSUE TITLE
Add more examples to.. examples (Si5351)

### ISSUE THREAD

**Issue by panciunio** [cnlohr/ch32v003fun#256]
Hi,

I'm not regular contributor and my knowledge regarding GIT API is rather weak... so I would ask how is procedure to add more examples to examples branch? For example I adapted I2C function to be more generic and add feature to use VCXO Si5351 with CH32V003. Maybe someone needs this kind of devices...

https://github.com/panciunio/ch32v003fun/tree/master/projects

Best Regards,
pancio

**Comment by cnlohr** [comment]
For this sort of thing, you should probably make a separate project on github, then I can link it in the readme!

**Comment by cnlohr** [comment]
Please open a new issue if/when you do add it!
