### ISSUE TITLE
FUN_HIGH and FUN_LOW behave reversed for funDigitalWrite

### ISSUE THREAD

**Issue by ahhuhtal** [cnlohr/ch32v003fun#270]
`#define funDigitalWrite( pin, value ) { GpioOf( pin )->BSHR = 1<<((value)*16 + ((pin) & 0xf)); }`

funDigitalWrite operates by shifting a 1 to either the set bit of the pin (positions 0 through 7) or the reset bit of the pin (positions 16 through 23). This is a pretty clever approach. However, with `value=FUN_HIGH` (defined as 1) the bit will be at position 16+pin, while for `value=FUN_LOW` (defined as 0) the bit will be at position 0+pin. This is opposite of what is expected (or at least what I would expect).

A tempting solution would be to just reverse the definitions, but this would e.g. break compatibility with `funDigitalRead`, and be all kinds of confusing in general.

Suggestions:
1. `#define funDigitalWrite( pin, value ) { GpioOf( pin )->BSHR = (0x10000 | (value))<<((pin) & 0xf); }`
2. `#define funDigitalWrite( pin, value ) { GpioOf( pin )->BSHR = 1<<((!value)*16 + ((pin) & 0xf)); }`

Option 1 works because reset and set together results in a set.

**Comment by cnlohr** [comment]
WOW... 

Side-note #2 is def better because it forces nonzero values to become "true" and 0 to be "false"

Thank you SO MUCH for finding this and pointing it out.  I guess I just tested that the LED blunk not that it was the right on/off of the blink.
