### ISSUE TITLE
how to reset/reboot the chip when flash done via minichlink?

### ISSUE THREAD

**Issue by chrizw** [cnlohr/ch32v003fun#313]
I installed the driver via zig and succeeded flash the ch32v003 chip. but it halt and could not automatic reset. tring use minichlink -e, but it doesnt works. 
How do I make the chip automatically restart after flash?

**Comment by prosper00** [comment]
when you do a 'make flash' it ends up issuing a 'minichlink -w binfile.bin flash -b'. It immediately begins execution for me.

**Comment by chrizw** [comment]
yes, I tried minichlink -b, and it reboot immediately, thanks.
