### ISSUE TITLE
ADC_CTLR1 Register bits do not match CH32V003 TRM

### ISSUE THREAD

**Issue by romain145** [cnlohr/ch32v003fun#319]
The bits DUALMOD[3:0] do not exist in the register ADC_CTLR1 on the CH32V003.
https://github.com/cnlohr/ch32v003fun/blob/e5a7958d27cb21cf7920f3790f7161b8d78a3a5b/ch32v003fun/ch32v003fun.h#L2526

![image](https://github.com/cnlohr/ch32v003fun/assets/4060945/45131ffa-02a9-4b9e-90fe-723b9ed46f7f)

**Comment by cnlohr** [comment]
Just because it's not in the TRM doesn't mean it's not useful - this came from the original EVT, so my expectation is that it may have just not functioned correctly.  No need to go back and retroactively remove it though.
