### ISSUE TITLE
(Suggestion) Add function for configuring pullup/down on inputs

### ISSUE THREAD

**Issue by jglim** [cnlohr/ch32v003fun#327]
Hello!

While interfacing the ch32v003 with a rotary encoder, I could not find a quick and "easy" way to configure the input pins as pullups, so I wrote this snippet:

```c
#define FUN_INPUT_PULLUP 1
#define FUN_INPUT_PULLDOWN 0

#define funInputPullUpDown( pin, mode ) { GpioOf( pin )->OUTDR = (GpioOf( pin )->OUTDR & ~(1 << (pin & 0xf))) | (mode << (pin & 0xf)); }
```
It can be used like this:
```c
// configure a pin (PC5 in this case) into an input that uses pullup/down 
funPinMode(PC5, GPIO_Speed_In | GPIO_CNF_IN_PUPD);

// actually enable the pullup
funInputPullUpDown(PC5, FUN_INPUT_PULLUP);

...
// read the state
funDigitalRead(PC5);
```

I've opened this issue to share this as I thought it might come in handy. If it looks like something that could be added to `ch32v003fun.h`, I'll be glad to send a PR.

---

On a tangent, I ordered a bunch of boards for those encoders which turned up today, and they _just work_ because of ch32v003fun. Thank you cnlohr and other contributors for making such a useful project!

![image](https://github.com/cnlohr/ch32v003fun/assets/1116555/46b7f6e5-8961-4c15-88d1-cc2bb9422033)

**Comment by eeucalyptus** [comment]
`funInputPullUpDown` does the same thing as `funDigitalWrite`, with an additional read access, because it uses the OUTDR directly instead of the BSHR. I recommend using `funDigitalWrite` instead, but it will hardly make a difference 95% of cases.
