### ISSUE TITLE
Which USB driver are you using for the CH-link?

### ISSUE THREAD

**Issue by Rockwell1799** [cnlohr/ch32v003fun#328]
For some reason, I can't get minichlink to work, it's complaining about "bad USB device".I tried winusb and libusb using Zadig,but no luck! I'm using windows 11.

**Comment by Rockwell1799** [comment]
I managed to install WinUsb on interface 0 and my CH-Link is now recognized, but when sending the command : minichlink.exe -u to unbrick the device (CH32V003) I get the following message:
Error sending WCH command (on recv): 81 0d 01 0f 09
Can someone help me please?

**Comment by Rockwell1799** [comment]
Never mind ! I found a solution by myself!

**Comment by cnlohr** [comment]
What was the solution?  

Sorry I was out for a few days?

**Comment by cnlohr** [comment]
Was your programmer in ARM mode? Did you need to do the hold-mode-button-and-reboot it?

**Comment by Rockwell1799** [comment]
Because my CH32V003 was bricked, I was getting that error, so, I had only to plug the CH-LINKE without the microcontroller connected, execute the command then plug the MCU back.

**Comment by cnlohr** [comment]
Ah! Thanks! I am surprised that didn't get fixed by -u in general, but there do seem to be some corner cases.
