### ISSUE TITLE
funPinMode and Pull-up?

### ISSUE THREAD

**Issue by Rockwell1799** [cnlohr/ch32v003fun#387]
Hello
I'm trying to set up and pin as input and pull it up, but I can't find a way to do it using the Arduino like function funPinMode.
Am I missing something?

**Comment by TommyMurphyTM1234** [comment]
Duplicate of this issue? 

- https://github.com/cnlohr/ch32v003fun/issues/327

**Comment by eeucalyptus** [comment]
`funPinMode` already supports that just fine. There is the `GPIO_CFGLR_IN_PUPD` which enables that. PU/PD is selected with the output value, eg:
```
funPinMode(PC0, GPIO_CFGLR_IN_PUPD);
funDigitalWrite(PC0, FUN_HIGH);
```
