### ISSUE TITLE
Please consider opening ' Discussions ' option in this repo

### ISSUE THREAD

**Issue by Ganesharyal24894** [cnlohr/ch32v003fun#389]
I am trying to boot a RV processor from scratch without any boiler plate code, just for learning purpose and I have some doubts regarding ch32 and QingKeV2 processor. It would be nice to have 'Discussions' option opened as this is not really an issue and I would like to not flood the issues section.

**Comment by prosper00** [comment]
there's also Discord:

"
Support
You can open a github ticket or join my Discord in the #ch32v003fun channel. Right now invites are private, so just ping me @cnlohr for an invite link. My PMs are open.
"

**Comment by Ganesharyal24894** [comment]
Okay, I will head to discord then
