### ISSUE TITLE
GPIO issue with PC0 on QFN20 part

### ISSUE THREAD

**Issue by machdyne** [cnlohr/ch32v003fun#467]
Hello.

I'm wondering if anyone has had problems with PC0 on the CH32V003F4U6 (QFN20) part.

I'm unable to set the output high:

```
GPIOC->CFGLR &= ~(0xf<<(4*0));
GPIOC->CFGLR |= (GPIO_Speed_50MHz | GPIO_CNF_OUT_PP)<<(4*0);
GPIOC->BSHR = (1<<0);
```

The pin measures 0V. I've tried this on two boards and it doesn't seem to be a PCB issue. I've also tried it with the TSSOP20L part and it works as expected.

**Comment by machdyne** [comment]
Your description led me to realize my error, the schematic didn't match the PCB and PC0 wasn't connected to anything.

All is good now. Thank you and my apologies.

**Comment by dwillmore** [comment]
No worries, I'm glad you found the problem.  Don't feel bad, we've found plenty of real errors from similar reports and observations.  The important part is that someone learns something from this. :thumbsup:
