### ISSUE TITLE
Features for minichlink

### ISSUE THREAD

**Issue by cnlohr** [cnlohr/ch32v003fun#58]
* Ability to program option bytes reliably.
 * GDB support.

**Comment by recallmenot** [comment]
Aren't those the ones that can be used like EEPROM for non-volatile storage (settings)?

**Comment by cnlohr** [comment]
They work if you use optionbytes here, but it would be nice if you could just program it by command-line.  https://github.com/cnlohr/ch32v003fun/tree/master/examples/optionbytes

**Comment by cnlohr** [comment]
GDB Support is in and pretty good.  Still need option bytes.

**Comment by cnlohr** [comment]
It seems option bytes have been working for some time.
