### ISSUE TITLE
Add fence instruction for memory rewriting. 

### ISSUE THREAD

**Issue by cnlohr** [cnlohr/ch32v003fun#65]

**Comment by cnlohr** [comment]
(Memory writing of code)

**Comment by dwillmore** [comment]
Is this related to debugging?  Because there's no caches on this chip, so the only things you could be fighting with memory fences would be prefetch queues, etc.

**Comment by cnlohr** [comment]
I have not yet had an issue when debugging, but when I modified code in RAM, it was required. There is definitely _some_ kind of cache.

https://github.com/cnlohr/ch32v003fun/blob/master/examples/self_modify_code/self_modify_code.c#L50

Without this line, things don't work right.

**Comment by jnk0le** [comment]
Fetch of next instruction happens before the store is commited, most likely.

Shouldn't it be `fence.i`, btw?

**Comment by cnlohr** [comment]
I will have to experiment to see what is required.

**Comment by cnlohr** [comment]
It looks like this has not been and likely will not be an issue. I was worried something may be janky with debugging.
