### ISSUE TITLE
Invalid wch_link_command value in LEControl3v3

### ISSUE THREAD

**Issue by cw2** [cnlohr/ch32v003fun#67]
Hello,

  It seems the `wch_link_command` payload in `LEControl3v3()` function to disable 3v3 output is not correct (most likely copy-paste error) https://github.com/cnlohr/ch32v003fun/blob/master/minichlink/pgm-wch-linke.c#L180 - according to the actual data sent by WCH-LinkUtility it should be "\x81\x0d\x01\x0a" (reply 82 0d 01 0a).

  I can submit PR if needed...

**Comment by cnlohr** [comment]
Thank you. I will fix this (hopefully? tonight?)

@cw2 can you help me add some more functionality to the LinkE programmer? Would like to discuss on my Discord.  Specifically I really want to add printf-over-SWIO in addition to other improved debugability. 

https://discord.gg/MAgEcde4
