### ISSUE TITLE
esp32s2 programmer failed after second run on j4m6

### ISSUE THREAD

**Issue by phantomxe** [cnlohr/ch32v003fun#98]
I got some error message at try to program ch32v003's 8-pin package. It works on fresh chip but crashes when i try to upload new code.  

```
Found ESP32S2 Programmer
Error: Setup chip failed. Got code ffffffff
Could not setup interface.
``` 

I also tried minichlink -u mode. 

```
Found ESP32S2 Programmer
Entering Unbrick Mode
Connection starting
/0/ffffffff
/0/ffffffff
...
lots of ffffffff
...
ioctl (GFEATURE): Connection timed out
Error: Got error -1 when sending hid feature report.
Error: Flash is not unlocked (CTLR = ffeffdff)
```

**Comment by dwillmore** [comment]
Have you tried using the "-u" option of minichlink?  You need to let the programmer control power to the target if you aren't already.

**Comment by phantomxe** [comment]
I added power control circuit with pair of mosfets to GPIO11 and tried `minichlink -u` again.

```
Found ESP32S2 Programmer
Entering Unbrick Mode
Connection starting
/0/ffffffff
/0/ffffffff
/0/ffffffff
/0/ffffffff
/0/ffffffff
/0/ffffffff
/0/004c0c82
Flash unlocked
Whole-chip erase
Whole Chip Erase Code: 0
```

Seems to work. But when i try to program not working.

```
Found ESP32S2 Programmer
Error: Setup chip failed. Got code ffffffff
Could not setup interface.
```

**Comment by cnlohr** [comment]
Two thoughts:
I have seen situations where the whole-chip erase was unsuccessful - can you try `minichlink -ua`  If that works, let me know and I can make that default behavior.

**Comment by phantomxe** [comment]
`minichlink -ua` worked! I can reprogram chip without any issues now.

![waveform2](https://github.com/cnlohr/ch32v003fun/assets/22988043/d5e486f4-14e4-4393-bf8d-52a11861ea64)
